//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.26 at 01:04:13 AM EET 
//


package org.xmlsoap.schemas.devprof;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeviceEventingFilterDialectURIs.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DeviceEventingFilterDialectURIs">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyURI">
 *     &lt;enumeration value="http://schemas.xmlsoap.org/ws/2006/02/devprof/Action"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DeviceEventingFilterDialectURIs")
@XmlEnum
public enum DeviceEventingFilterDialectURIs {

    @XmlEnumValue("http://schemas.xmlsoap.org/ws/2006/02/devprof/Action")
    Action("http://schemas.xmlsoap.org/ws/2006/02/devprof/Action");
    private final String value;

    DeviceEventingFilterDialectURIs(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DeviceEventingFilterDialectURIs fromValue(String v) {
        for (DeviceEventingFilterDialectURIs c: DeviceEventingFilterDialectURIs.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
