//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.26 at 01:04:13 AM EET 
//


package org.xmlsoap.schemas.devprof;

import java.net.URI;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import org.w3._2001.xmlschema.Adapter1;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.xmlsoap.schemas.devprof package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ThisDevice_QNAME = new QName("http://schemas.xmlsoap.org/ws/2006/02/devprof", "ThisDevice");
    private final static QName _ServiceId_QNAME = new QName("http://schemas.xmlsoap.org/ws/2006/02/devprof", "ServiceId");
    private final static QName _ThisModel_QNAME = new QName("http://schemas.xmlsoap.org/ws/2006/02/devprof", "ThisModel");
    private final static QName _Hosted_QNAME = new QName("http://schemas.xmlsoap.org/ws/2006/02/devprof", "Hosted");
    private final static QName _Profile_QNAME = new QName("http://schemas.xmlsoap.org/ws/2006/02/devprof", "Profile");
    private final static QName _Host_QNAME = new QName("http://schemas.xmlsoap.org/ws/2006/02/devprof", "Host");
    private final static QName _Types_QNAME = new QName("http://schemas.xmlsoap.org/ws/2006/02/devprof", "Types");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.xmlsoap.schemas.devprof
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HostServiceType }
     * 
     */
    public HostServiceType createHostServiceType() {
        return new HostServiceType();
    }

    /**
     * Create an instance of {@link ThisModelType }
     * 
     */
    public ThisModelType createThisModelType() {
        return new ThisModelType();
    }

    /**
     * Create an instance of {@link Relationship }
     * 
     */
    public Relationship createRelationship() {
        return new Relationship();
    }

    /**
     * Create an instance of {@link AssertionType }
     * 
     */
    public AssertionType createAssertionType() {
        return new AssertionType();
    }

    /**
     * Create an instance of {@link ThisDeviceType }
     * 
     */
    public ThisDeviceType createThisDeviceType() {
        return new ThisDeviceType();
    }

    /**
     * Create an instance of {@link LocalizedStringType }
     * 
     */
    public LocalizedStringType createLocalizedStringType() {
        return new LocalizedStringType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ThisDeviceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/ws/2006/02/devprof", name = "ThisDevice")
    public JAXBElement<ThisDeviceType> createThisDevice(ThisDeviceType value) {
        return new JAXBElement<ThisDeviceType>(_ThisDevice_QNAME, ThisDeviceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link URI }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/ws/2006/02/devprof", name = "ServiceId")
    @XmlJavaTypeAdapter(Adapter1 .class)
    public JAXBElement<URI> createServiceId(URI value) {
        return new JAXBElement<URI>(_ServiceId_QNAME, URI.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ThisModelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/ws/2006/02/devprof", name = "ThisModel")
    public JAXBElement<ThisModelType> createThisModel(ThisModelType value) {
        return new JAXBElement<ThisModelType>(_ThisModel_QNAME, ThisModelType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HostServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/ws/2006/02/devprof", name = "Hosted")
    public JAXBElement<HostServiceType> createHosted(HostServiceType value) {
        return new JAXBElement<HostServiceType>(_Hosted_QNAME, HostServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssertionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/ws/2006/02/devprof", name = "Profile")
    public JAXBElement<AssertionType> createProfile(AssertionType value) {
        return new JAXBElement<AssertionType>(_Profile_QNAME, AssertionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HostServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/ws/2006/02/devprof", name = "Host")
    public JAXBElement<HostServiceType> createHost(HostServiceType value) {
        return new JAXBElement<HostServiceType>(_Host_QNAME, HostServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link QName }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/ws/2006/02/devprof", name = "Types")
    public JAXBElement<List<QName>> createTypes(List<QName> value) {
        return new JAXBElement<List<QName>>(_Types_QNAME, ((Class) List.class), null, ((List<QName> ) value));
    }

}
