//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.26 at 01:04:13 AM EET 
//


package org.xmlsoap.schemas.devprof;

import java.net.URI;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import org.w3._2001.xmlschema.Adapter1;
import org.w3c.dom.Element;


/**
 * <p>Java class for ThisModelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ThisModelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Manufacturer" type="{http://schemas.xmlsoap.org/ws/2006/02/devprof}LocalizedStringType" maxOccurs="unbounded"/>
 *         &lt;element name="ManufacturerUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="ModelName" type="{http://schemas.xmlsoap.org/ws/2006/02/devprof}LocalizedStringType" maxOccurs="unbounded"/>
 *         &lt;element name="ModelNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ModelUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="PresentationUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThisModelType", propOrder = {
    "manufacturer",
    "manufacturerUrl",
    "modelName",
    "modelNumber",
    "modelUrl",
    "presentationUrl",
    "any"
})
public class ThisModelType {

    @XmlElement(name = "Manufacturer", required = true)
    protected List<LocalizedStringType> manufacturer;
    @XmlElement(name = "ManufacturerUrl", type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "anyURI")
    protected URI manufacturerUrl;
    @XmlElement(name = "ModelName", required = true)
    protected List<LocalizedStringType> modelName;
    @XmlElement(name = "ModelNumber")
    protected String modelNumber;
    @XmlElement(name = "ModelUrl", type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "anyURI")
    protected URI modelUrl;
    @XmlElement(name = "PresentationUrl", type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "anyURI")
    protected URI presentationUrl;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the manufacturer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manufacturer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManufacturer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalizedStringType }
     * 
     * 
     */
    public List<LocalizedStringType> getManufacturer() {
        if (manufacturer == null) {
            manufacturer = new ArrayList<LocalizedStringType>();
        }
        return this.manufacturer;
    }

    /**
     * Gets the value of the manufacturerUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public URI getManufacturerUrl() {
        return manufacturerUrl;
    }

    /**
     * Sets the value of the manufacturerUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerUrl(URI value) {
        this.manufacturerUrl = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modelName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModelName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalizedStringType }
     * 
     * 
     */
    public List<LocalizedStringType> getModelName() {
        if (modelName == null) {
            modelName = new ArrayList<LocalizedStringType>();
        }
        return this.modelName;
    }

    /**
     * Gets the value of the modelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelNumber() {
        return modelNumber;
    }

    /**
     * Sets the value of the modelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelNumber(String value) {
        this.modelNumber = value;
    }

    /**
     * Gets the value of the modelUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public URI getModelUrl() {
        return modelUrl;
    }

    /**
     * Sets the value of the modelUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelUrl(URI value) {
        this.modelUrl = value;
    }

    /**
     * Gets the value of the presentationUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public URI getPresentationUrl() {
        return presentationUrl;
    }

    /**
     * Sets the value of the presentationUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentationUrl(URI value) {
        this.presentationUrl = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

    // Helper Methods

    public void addManufacturer(LocalizedStringType str){
    	getManufacturer().add(str);
    }
    
    public void setManufacturer(String name){
    	getManufacturer().add(new LocalizedStringType("",name));
    }
    
    public String getManufacturer(String locale){
    	for(LocalizedStringType m : getManufacturer()){
    		if(m.getLocale().equalsIgnoreCase(locale)){
    			return m.getValue();
    		}
    	}
    	return null;
    }
    
    public void addModelName(LocalizedStringType str){
    	getModelName().add(str);
    }
    
    public void setModelName(String name){
    	getModelName().add(new LocalizedStringType("",name));
    }
    
    public String getModelName(String locale){
    	if(locale == null){
    		locale = "";
    	}
    	for(LocalizedStringType m : getManufacturer()){
    		if(m.getLocale().equalsIgnoreCase(locale)){
    			return m.getValue();
    		}
    	}
    	return null;
    }
    
    public void addAny(Object o){
    	getAny().add(o);
    }
    
    public void addOtherAttribute(QName name, String value){
    	getOtherAttributes().put(name, value);
    }
    
    public String getOtherAttribute(QName name){
    	return getOtherAttributes().get(name);
    }
    
    
}
