//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.07 at 12:15:47 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.xmlsoap.org/ws/2005/04/discovery", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.xmlsoap.schemas.discovery;
